#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:8189cf0a45306137d245c98e212f7c29379f3d11ca4cc549c1b97aadcd813846
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/calicoctl" \
    "https://github.com/projectcalico/calico/releases/download/v${version}/calicoctl-linux-${alt_arch}"
chmod +x "${prefix}${target}/bin/calicoctl"
EOF