#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:603df81cedf0e7d932932147512697e3d846a73733f9329e77910d38c8c846be
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/helmfile" \
    "https://github.com/roboll/helmfile/releases/download/v${version}/helmfile_linux_${alt_arch}"
chmod +x "${prefix}${target}/bin/helmfile"
curl --silent --location --fail --output "${prefix}${target}/share/bash-completion/completions/helmfile" \
    "https://github.com/roboll/helmfile/raw/v${version}/autocomplete/helmfile_bash_autocomplete"
curl --silent --location --fail --output "${prefix}${target}/share/zsh/vendor-completions/_helmfile" \
    "https://github.com/roboll/helmfile/raw/v${version}/autocomplete/helmfile_zsh_autocomplete"
EOF