#syntax=docker/dockerfile:1.6.0

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
check-github-release-asset "rupor-github/win-gpg-agent" "${version}" "win-gpg-agent.zip"
curl --silent --location --fail --remote-name "https://github.com/rupor-github/win-gpg-agent/releases/download/v${version}/win-gpg-agent.zip"
unzip -q -o -d "/tmp" "win-gpg-agent.zip"
rm "win-gpg-agent.zip"
mv "/tmp/sorelay.exe" "${prefix}${target}/bin"
EOF