#syntax=docker/dockerfile:1.5.1

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/kube-score" \
    "https://github.com/zegl/kube-score/releases/download/v${version}/kube-score_${version}_linux_${alt_arch}"
chmod +x "${prefix}${target}/bin/kube-score"
EOF