#syntax=docker/dockerfile:1.4.3

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location "https://github.com/cheat/cheat/releases/download/${version}/cheat-linux-${alt_arch}.gz" \
| gunzip \
>"${prefix}${target}/bin/cheat"
chmod +x "${prefix}${target}/bin/cheat"

curl --silent --location --output "${prefix}${target}/share/man/man1/cheat.1" \
    "https://github.com/cheat/cheat/raw/${version}/doc/cheat.1"
EOF