#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:603df81cedf0e7d932932147512697e3d846a73733f9329e77910d38c8c846be
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail "https://github.com/cheat/cheat/releases/download/${version}/cheat-linux-${alt_arch}.gz" \
| gunzip \
>"${prefix}${target}/bin/cheat"
chmod +x "${prefix}${target}/bin/cheat"

curl --silent --location --fail --output "${prefix}${target}/share/man/man1/cheat.1" \
    "https://github.com/cheat/cheat/raw/${version}/doc/cheat.1"
EOF