#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:603df81cedf0e7d932932147512697e3d846a73733f9329e77910d38c8c846be

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/clusterctl" \
    "https://github.com/kubernetes-sigs/cluster-api/releases/download/v${version}/clusterctl-linux-${alt_arch}"
chmod +x "${prefix}${target}/bin/clusterctl"
"${prefix}${target}/bin/clusterctl" completion bash >"${prefix}${target}/share/bash-completion/completions/clusterctl"
"${prefix}${target}/bin/clusterctl" completion zsh >"${prefix}${target}/share/zsh/vendor-completions/_clusterctl"
EOF