#syntax=docker/dockerfile:1.4.3

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --output "${prefix}${target}/bin/ctop" \
    "https://github.com/bcicen/ctop/releases/download/v${version}/ctop-${version}-linux-${alt_arch}"
chmod +x "${prefix}${target}/bin/ctop"
EOF