#syntax=docker/dockerfile:1.6.0

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
check-github-release-asset "bcicen/ctop" "v${version}" "ctop-${version}-linux-${alt_arch}"
curl --silent --location --fail --output "${prefix}${target}/bin/ctop" \
    "https://github.com/bcicen/ctop/releases/download/v${version}/ctop-${version}-linux-${alt_arch}"
chmod +x "${prefix}${target}/bin/ctop"
EOF