#syntax=docker/dockerfile:1.6.0

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
check-github-release-asset "cloudflare/cloudflared" "${version}" "cloudflared-linux-${alt_arch}"
curl --silent --location --fail --output "${prefix}${target}/bin/cloudflared" \
    "https://github.com/cloudflare/cloudflared/releases/download/${version}/cloudflared-linux-${alt_arch}"
chmod +x "${prefix}${target}/bin/cloudflared"
EOF