#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
# check-github-release-asset "foo/bar" "${version}" "foo-${version}-linux-amd64.tar.gz"
curl --silent --location --fail --output "${prefix}${target}/bin/dinit" \
    "https://gitlab.com/tozd/dinit/-/releases/v${version}/downloads/linux-${alt_arch}/dinit"
chmod +x "${prefix}${target}/bin/dinit"
EOF