#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-github-release-asset "instrumenta/kubeval" "v${version}" "kubeval-linux-${alt_arch}.tar.gz"
curl --silent --location --fail "https://github.com/instrumenta/kubeval/releases/download/v${version}/kubeval-linux-${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}${target}/bin" --no-same-owner \
    kubeval
EOF