#syntax=docker/dockerfile:1.4.3

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/mkcert" \
    "https://github.com/FiloSottile/mkcert/releases/download/v${version}/mkcert-v${version}-linux-${alt_arch}"
chmod +x "${prefix}${target}/bin/mkcert"
EOF