#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-github-release-asset "FiloSottile/mkcert" "v${version}" "mkcert-v${version}-linux-${alt_arch}"
curl --silent --location --fail --output "${prefix}${target}/bin/mkcert" \
    "https://github.com/FiloSottile/mkcert/releases/download/v${version}/mkcert-v${version}-linux-${alt_arch}"
chmod +x "${prefix}${target}/bin/mkcert"
EOF