FROM debian:11
RUN apt-get update \
 && apt-get -y install --no-install-recommends \
        curl \
        ca-certificates \
        iptables \
        procps \
 && update-alternatives --set iptables /usr/sbin/iptables-legacy
COPY test.sh /
COPY docker-setup.sh /