FROM alpine:3.15
RUN apk add --update-cache --no-cache \
        bash \
        curl \
        ca-certificates \
        procps \
        iptables \
        shadow \
        openrc \
        git \
 && mkdir -p /run/openrc \
 && touch /run/openrc/softlevel
COPY test/test.sh /
COPY docker-setup.sh /