#syntax=docker/dockerfile:1.5.2

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
COPY <<EOF ${prefix}${target}/var/cache/uniget/npm-is-included-in-prebuilt-binaries-of-nodejs