#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:8189cf0a45306137d245c98e212f7c29379f3d11ca4cc549c1b97aadcd813846

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

RUN <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    zsh
EOF

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/earthly" \
    "https://github.com/earthly/earthly/releases/download/v${version}/earthly-linux-amd64"
chmod +x "${prefix}${target}/bin/earthly"
"${prefix}${target}/bin/earthly" bootstrap --with-autocomplete --no-buildkit
cp /usr/share/bash-completion/completions/earthly "${prefix}${target}/share/bash-completion/completions/earthly"
sed -i "s|${prefix}||" "${prefix}${target}/share/bash-completion/completions/earthly"
cp /usr/local/share/zsh/site-functions/_earthly "${prefix}${target}/share/zsh/vendor-completions/_earthly"
sed -i "s|${prefix}||" "${prefix}${target}/share/zsh/vendor-completions/_earthly"
EOF