#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:603df81cedf0e7d932932147512697e3d846a73733f9329e77910d38c8c846be
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/ignite" \
    "https://github.com/weaveworks/ignite/releases/download/v${version}/ignite-${alt_arch}"
chmod +x "${prefix}${target}/bin/ignite"
curl --silent --location --fail --output "${prefix}${target}/bin/ignited" \
    "https://github.com/weaveworks/ignite/releases/download/v${version}/ignited-${alt_arch}"
chmod +x "${prefix}${target}/bin/ignited"
"${prefix}${target}/bin/ignite"  completion >"${prefix}${target}/share/bash-completion/completions/ignite"
"${prefix}${target}/bin/ignited" completion >"${prefix}${target}/share/bash-completion/completions/ignited" || true
EOF