#syntax=docker/dockerfile:1.5.2

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/python:${ref} AS python
FROM ghcr.io/nicholasdille/docker-setup/shiv:${ref} AS shiv

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
COPY --link --from=python / /
COPY --link --from=shiv / /
ARG name
ARG version
RUN <<EOF
for BINARY in sbomgrep sbomls sbomrm sbomupdate; do
    shiv --output-file "${prefix}${target}/bin/${BINARY}" --console-script "${BINARY}" "sbomtools==${version}"
done
EOF