#syntax=docker/dockerfile:1.5.1

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
curl --silent --location --fail "https://github.com/helm/chart-testing/releases/download/v${version}/chart-testing_${version}_linux_${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}${target}/bin/" --no-same-owner \
    ct \
    etc
mkdir -p "${prefix}/etc/ct"
mv "${prefix}${target}/bin/etc/chart_schema.yaml" "${prefix}/etc/ct/"
mv "${prefix}${target}/bin/etc/lintconf.yaml" "${prefix}/etc/ct/"
rmdir "${prefix}${target}/bin/etc"

"${prefix}${target}/bin/ct" completion bash >"${prefix}${target}/share/bash-completion/completions/ct"
"${prefix}${target}/bin/ct" completion fish >"${prefix}${target}/share/fish/vendor_completions.d/ct.fish"
"${prefix}${target}/bin/ct" completion zsh >"${prefix}${target}/share/zsh/vendor-completions/_ct"
EOF
