#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-github-release-asset "Jabba-Team/jabba" "${version}" "jabba-${version}-linux-${alt_arch}"
curl --silent --location --fail --output "${prefix}${target}/bin/jabba" \
    "https://github.com/Jabba-Team/jabba/releases/download/${version}/jabba-${version}-linux-${alt_arch}"
chmod +x "${prefix}${target}/bin/jabba"
EOF