#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:603df81cedf0e7d932932147512697e3d846a73733f9329e77910d38c8c846be

FROM ghcr.io/nicholasdille/docker-setup/python:${ref} AS python
FROM ghcr.io/nicholasdille/docker-setup/shiv:${ref} AS shiv

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
COPY --link --from=python / /
COPY --link --from=shiv / /
ARG name
ARG version
RUN <<EOF
shiv --output-file "${prefix}${target}/bin/yamllint" --console-script yamllint "yamllint==${version}"
EOF