#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-github-release-asset "rancher/gitjob" "v${version}" "gitjob-${alt_arch}"
curl --silent --location --fail --output "${prefix}${target}/bin/gitjob" \
    "https://github.com/rancher/gitjob/releases/download/v${version}/gitjob-${alt_arch}"
chmod +x "${prefix}${target}/bin/gitjob"
EOF