#syntax=docker/dockerfile:1.4.3

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --output "${prefix}${target}/bin/gitjob" \
    "https://github.com/rancher/gitjob/releases/download/v${version}/gitjob-amd64"
chmod +x "${prefix}${target}/bin/gitjob"
EOF