#syntax=docker/dockerfile:1.5.1

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
url="https://github.com/grafana/loki/releases/download/v${version}/loki-linux-${alt_arch}.zip"
filename="$(basename "${url}")"
curl --silent --location --fail --remote-name "${url}"
unzip -q -o -d "${prefix}${target}/bin" "${filename}"
mv "${prefix}${target}/bin/loki-linux-${alt_arch}" "${prefix}${target}/bin/loki"
EOF