#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:8189cf0a45306137d245c98e212f7c29379f3d11ca4cc549c1b97aadcd813846

FROM ghcr.io/nicholasdille/docker-setup/go-md2man:${ref} AS go-md2man

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
COPY --link --from=go-md2man / /
RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/runc" \
    "https://github.com/opencontainers/runc/releases/download/v${version}/runc.${alt_arch}"
chmod +x "${prefix}${target}/bin/runc"
EOF
RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/share/man/man8/runc-checkpoint.8.md" \
    "https://github.com/opencontainers/runc/raw/v${version}/man/runc-checkpoint.8.md"
curl --silent --location --fail --output "${prefix}${target}/share/man/man8/runc-create.8.md" \
    "https://github.com/opencontainers/runc/raw/v${version}/man/runc-create.8.md"
curl --silent --location --fail --output "${prefix}${target}/share/man/man8/runc-delete.8.md" \
    "https://github.com/opencontainers/runc/raw/v${version}/man/runc-delete.8.md"
curl --silent --location --fail --output "${prefix}${target}/share/man/man8/runc-events.8.md" \
    "https://github.com/opencontainers/runc/raw/v${version}/man/runc-events.8.md"
curl --silent --location --fail --output "${prefix}${target}/share/man/man8/runc-exec.8.md" \
    "https://github.com/opencontainers/runc/raw/v${version}/man/runc-exec.8.md"
curl --silent --location --fail --output "${prefix}${target}/share/man/man8/runc-kill.8.md" \
    "https://github.com/opencontainers/runc/raw/v${version}/man/runc-kill.8.md"
curl --silent --location --fail --output "${prefix}${target}/share/man/man8/runc-list.8.md" \
    "https://github.com/opencontainers/runc/raw/v${version}/man/runc-list.8.md"
curl --silent --location --fail --output "${prefix}${target}/share/man/man8/runc-pause.8.md" \
    "https://github.com/opencontainers/runc/raw/v${version}/man/runc-pause.8.md"
curl --silent --location --fail --output "${prefix}${target}/share/man/man8/runc-ps.8.md" \
    "https://github.com/opencontainers/runc/raw/v${version}/man/runc-ps.8.md"
curl --silent --location --fail --output "${prefix}${target}/share/man/man8/runc-restore.8.md" \
    "https://github.com/opencontainers/runc/raw/v${version}/man/runc-restore.8.md"
curl --silent --location --fail --output "${prefix}${target}/share/man/man8/runc-resume.8.md" \
    "https://github.com/opencontainers/runc/raw/v${version}/man/runc-resume.8.md"
curl --silent --location --fail --output "${prefix}${target}/share/man/man8/runc-run.8.md" \
    "https://github.com/opencontainers/runc/raw/v${version}/man/runc-run.8.md"
curl --silent --location --fail --output "${prefix}${target}/share/man/man8/runc-spec.8.md" \
    "https://github.com/opencontainers/runc/raw/v${version}/man/runc-spec.8.md"
curl --silent --location --fail --output "${prefix}${target}/share/man/man8/runc-start.8.md" \
    "https://github.com/opencontainers/runc/raw/v${version}/man/runc-start.8.md"
curl --silent --location --fail --output "${prefix}${target}/share/man/man8/runc-state.8.md" \
    "https://github.com/opencontainers/runc/raw/v${version}/man/runc-state.8.md"
curl --silent --location --fail --output "${prefix}${target}/share/man/man8/runc-update.8.md" \
    "https://github.com/opencontainers/runc/raw/v${version}/man/runc-update.8.md"
curl --silent --location --fail --output "${prefix}${target}/share/man/man8/runc.8.md" \
    "https://github.com/opencontainers/runc/raw/v${version}/man/runc.8.md"
MANPAGES="$(find "${prefix}${target}/share/man/man8" -type f -name \*.md)"
for FILE in ${MANPAGES}; do
    DEST_FILE="$(basename "${FILE}" .md)"
    DEST_DIR="$(dirname "${FILE}")"
    DEST="${DEST_DIR}/${DEST_FILE}"
    echo "Converting ${FILE} to ${DEST}"
    go-md2man -in "${FILE}" -out "${DEST}"
    rm "${FILE}"
done
EOF