#syntax=docker/dockerfile:1.5.1

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/dasel" \
    "https://github.com/TomWright/dasel/releases/download/v${version}/dasel_linux_${alt_arch}"
chmod +x "${prefix}${target}/bin/dasel"
EOF