#syntax=docker/dockerfile:1.4.3

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/hadolint" \
    "https://github.com/hadolint/hadolint/releases/download/v${version}/hadolint-Linux-${arch}"
chmod +x "${prefix}${target}/bin/hadolint"
EOF