#syntax=docker/dockerfile:1.4.3

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/linuxkit" \
    "https://github.com/linuxkit/linuxkit/releases/download/v${version}/linuxkit-linux-${alt_arch}"
chmod +x "${prefix}${target}/bin/linuxkit"
EOF