#syntax=docker/dockerfile:1.5.1

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/jp" \
    "https://github.com/jmespath/jp/releases/download/${version}/jp-linux-${alt_arch}"
chmod +x "${prefix}${target}/bin/jp"
EOF