#syntax=docker/dockerfile:1.5.2

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
curl --silent --location --fail "https://github.com/containers/youki/releases/download/v${version}/youki_${version//./_}_linux.tar.gz" \
| tar --extract --gzip --directory="${prefix}${target}/bin/" --strip-components=2 --no-same-owner \
    "youki_${version//./_}_linux/youki-${version}/youki"
EOF