#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:603df81cedf0e7d932932147512697e3d846a73733f9329e77910d38c8c846be

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/k8s-tew" \
    "https://github.com/darxkies/k8s-tew/releases/download/${version}/k8s-tew"
chmod +x "${prefix}${target}/bin/k8s-tew"

"${prefix}${target}/bin/k8s-tew" completion bash >"${prefix}${target}/share/bash-completion/completions/k8s-tew"
"${prefix}${target}/bin/k8s-tew" completion zsh >"${prefix}${target}/share/zsh/vendor-completions/_k8s-tew"
EOF