#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
curl --silent --location --fail "https://github.com/kubernetes-sigs/cri-tools/releases/download/v${version}/crictl-v${version}-linux-${alt_arch}.tar.gz" \
| tar --extract --gzip --directory "${prefix}${target}/bin/" --no-same-owner
EOF
COPY crictl.yaml "${prefix}/etc/"