#syntax=docker/dockerfile:1.5.1

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/ketch" \
    "https://github.com/theketchio/ketch/releases/download/v${version}/ketch-linux-amd64"
chmod +x "${prefix}${target}/bin/ketch"
EOF