#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:603df81cedf0e7d932932147512697e3d846a73733f9329e77910d38c8c846be
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/ketch" \
    "https://github.com/theketchio/ketch/releases/download/v${version}/ketch-linux-amd64"
chmod +x "${prefix}${target}/bin/ketch"
EOF