#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
url="https://github.com/projectdiscovery/mapcidr/releases/download/v${version}/mapcidr_${version}_linux_${alt_arch}.zip"
filename="$(basename "${url}")"
curl --silent --location --fail --remote-name "${url}"
unzip -q -o -d "${prefix}${target}/bin" "${filename}"
rm \
    "${prefix}${target}/bin/LICENSE.MD" \
    "${prefix}${target}/bin/README.md"
EOF