#syntax=docker/dockerfile:1.5.1

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail "https://github.com/mhausenblas/cinf/releases/download/v${version}/cinf_linux_${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}${target}/bin" --no-same-owner \
    cinf
EOF