#syntax=docker/dockerfile:1.6.0

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
check-github-release-asset "docker/machine" "v${version}" "docker-machine-Linux-${arch}"
curl --silent --location --fail --output "${prefix}${target}/bin/docker-machine" \
    "https://github.com/docker/machine/releases/download/v${version}/docker-machine-Linux-${arch}"
chmod +x "${prefix}${target}/bin/docker-machine"
EOF