#syntax=docker/dockerfile:1.4.3

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --output "${prefix}${target}/bin/docker-machine" \
    "https://github.com/docker/machine/releases/download/v${version}/docker-machine-Linux-${arch}"
chmod +x "${prefix}${target}/bin/docker-machine"
EOF