#syntax=docker/dockerfile:1.5.1

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
curl --silent --location --fail "https://github.com/cloudflare/cloudflare-go/releases/download/v${version}/flarectl_${version}_linux_${alt_Arch}.tar.xz" \
| tar --extract --xz --directory="${prefix}${target}/bin/" --no-same-owner \
    flarectl
EOF