#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:8189cf0a45306137d245c98e212f7c29379f3d11ca4cc549c1b97aadcd813846
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --remote-name "https://github.com/crra/mp3binder/releases/download/v${version}/linux_${alt_arch}.zip"
unzip -q -o -d "/tmp" "linux_${alt_arch}.zip"
rm "linux_${alt_arch}.zip"
mv "/tmp/mp3binder" "${prefix}${target}/bin"
EOF