#syntax=docker/dockerfile:1.5.1

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail "https://github.com/arttor/helmify/releases/download/v${version}/helmify_${version}_Linux_64-bit.tar.gz" \
| tar --extract --gzip --directory="${prefix}${target}/bin" --no-same-owner
EOF