#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-github-release-asset "cilium/pwru" "v${version}" "pwru-linux-${alt_arch}.tar.gz"
curl --silent --location --fail "https://github.com/cilium/pwru/releases/download/v${version}/pwru-linux-${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}${target}/bin" --no-same-owner
EOF