#syntax=docker/dockerfile:1.5.2

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
curl --silent --location --fail "https://github.com/wasmerio/wasmer/releases/download/v${version}/wasmer-linux-${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}${target}" --no-same-owner \
    bin
EOF