#syntax=docker/dockerfile:1.5.1

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/fx" \
    "https://github.com/antonmedv/fx/releases/download/${version}/fx_linux_${alt_arch}"
chmod +x "${prefix}${target}/bin/fx"
EOF