#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-github-release-asset "antonmedv/fx" "${version}" "fx_linux_${alt_arch}"
curl --silent --location --fail --output "${prefix}${target}/bin/fx" \
    "https://github.com/antonmedv/fx/releases/download/${version}/fx_linux_${alt_arch}"
chmod +x "${prefix}${target}/bin/fx"
EOF