#syntax=docker/dockerfile:1.5.1

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
url="https://github.com/projectdiscovery/dnsx/releases/download/v${version}/dnsx_${version}_linux_${alt_arch}.zip"
filename="$(basename "${url}")"
curl --silent --location --fail --remote-name "${url}"
unzip -q -o -d "${prefix}${target}/bin" "${filename}" \
    dnsx
EOF