#syntax=docker/dockerfile:1.5.2

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
url="https://github.com/superbrothers/ksort/releases/download/v${version}/ksort-linux-${alt_arch}.zip"
filename="$(basename "${url}")"
curl --silent --location --fail --remote-name "${url}"
unzip -q -o -d /tmp "${filename}"
mv /tmp/ksort "${prefix}${target}/bin/"
EOF