#syntax=docker/dockerfile:1.4.3

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
curl --silent --location --fail "https://github.com/casey/just/releases/download/${version}/just-${version}-x86_64-unknown-linux-musl.tar.gz" \
| tar --extract --gzip --directory="${prefix}${target}/bin/" --no-same-owner \
    just \
    just.1
mv "${prefix}${target}/bin/just.1" "${prefix}${target}/share/man/man1/"
EOF