#syntax=docker/dockerfile:1.5.1

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/semver" \
    "https://github.com/fsaintjacques/semver-tool/raw/${version}/src/semver"
chmod +x "${prefix}${target}/bin/semver"
EOF