#syntax=docker/dockerfile:1.4.3

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location https://github.com/aquasecurity/trivy/releases/download/v${version}/trivy_${version}_Linux-64bit.tar.gz \
| tar --extract --gzip --directory="${prefix}${target}/bin" \
      trivy \
      contrib
mkdir -p "${prefix}${target}/share/trivy"
mv "${prefix}${target}/bin/contrib" "${prefix}${target}/share/trivy/"
EOF

RUN <<EOF
curl --silent --location --output "${prefix}${target}/share/trivy/contrib/sonarqube.tpl" \
      https://github.com/mendhak/trivy-template-output-to-sonarqube/raw/master/sonarqube.tpl
EOF