#syntax=docker/dockerfile:1.4.2

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name=cni
ARG version=1.1.1

RUN <<EOF
mkdir -p "${prefix}${target}/libexec/cni"
curl -sL "https://github.com/containernetworking/plugins/releases/download/v${version}/cni-plugins-linux-${alt_arch}-v${version}.tgz" \
| tar -xz --directory="${prefix}${target}/libexec/cni" --no-same-owner
EOF