#syntax=docker/dockerfile:1.4.3

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
mkdir -p "${prefix}${target}/libexec/cni"
curl --silent --location --fail "https://github.com/containernetworking/plugins/releases/download/v${version}/cni-plugins-linux-${alt_arch}-v${version}.tgz" \
| tar --extract --gzip --directory="${prefix}${target}/libexec/cni" --no-same-owner
EOF