#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-github-release-asset "tsl0922/ttyd" "${version}" "ttyd.${arch}"
curl --silent --location --fail --output "${prefix}${target}/bin/ttyd" \
    "https://github.com/tsl0922/ttyd/releases/download/${version}/ttyd.${arch}"
chmod +x "${prefix}${target}/bin/ttyd"
EOF