#syntax=docker/dockerfile:1.4.3

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/duffle" \
    "https://github.com/cnabio/duffle/releases/download/${version}/duffle-linux-${alt_arch}"
chmod +x "${prefix}${target}/bin/duffle"
EOF