#syntax=docker/dockerfile:1.6.0

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

COPY docker ${prefix}${target}/libexec/podman/
RUN <<EOF
ln --symbolic --relative --force "${prefix}${target}/libexec/podman/docker" "${target}/bin/docker"
EOF