#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-github-release-asset "vmware-tanzu/buildkit-cli-for-kubectl" "v${version}" "linux-v${version}.tgz"
curl --silent --location --fail "https://github.com/vmware-tanzu/buildkit-cli-for-kubectl/releases/download/v${version}/linux-v${version}.tgz" \
| tar --extract --gzip --directory="${prefix}${target}/bin" --no-same-owner 
EOF