FROM fedora:35
RUN dnf install -y \
        cpio \
 && dnf install -y \
        procps-ng \
        iptables-legacy \
        initscripts \
        git \
        unzip \
        ncurses
COPY test/run.sh /
COPY docker-setup.sh /