#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:8189cf0a45306137d245c98e212f7c29379f3d11ca4cc549c1b97aadcd813846

FROM ubuntu:22.04@sha256:2adf22367284330af9f832ffefb717c78239f6251d9d0f58de50b86229ed1427 AS build
WORKDIR /tmp/tig
ARG name
ARG version
RUN <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    curl \
    ca-certificates \
    gcc \
    ncurses-dev \
    make
EOF
RUN <<EOF
curl --silent --location --fail "https://github.com/jonas/tig/releases/download/tig-${version}/tig-${version}.tar.gz" \
| tar --extract --gzip --strip-components=1
./configure
make prefix=/usr/local
make install install-doc-man prefix=/usr/local
mkdir -p \
    /usr/local/share/bash-completion/completions \
    /usr/local/share/zsh/vendor-completions
cp contrib/tig-completion.bash "/usr/local/share/bash-completion/completions/tig"
cp contrib/tig-completion.zsh "/usr/local/share/zsh/vendor-completions/_tig"
rm /usr/local/man
rm /usr/local/sbin/unminimize
EOF

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
COPY --from=build /usr/local/ ${prefix}${target}/