#syntax=docker/dockerfile:1.4.3

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

COPY kubelet.service ${prefix}/etc/systemd/system/

RUN <<EOF
curl --silent --location --output "${prefix}${target}/bin/kubelet" \
    "https://storage.googleapis.com/kubernetes-release/release/v${version}/bin/linux/${alt_arch}/kubelet"
chmod +x "${prefix}${target}/bin/kubelet"
EOF