#syntax=docker/dockerfile:1.5.1

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/img" \
    "https://github.com/genuinetools/img/releases/download/v${version}/img-linux-${alt_arch}"
chmod +x "${prefix}${target}/bin/img"
EOF