#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-github-release-asset "genuinetools/img" "v${version}" "img-linux-${alt_arch}"
curl --silent --location --fail --output "${prefix}${target}/bin/img" \
    "https://github.com/genuinetools/img/releases/download/v${version}/img-linux-${alt_arch}"
chmod +x "${prefix}${target}/bin/img"
EOF