#syntax=docker/dockerfile:1.5.1

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/faas-cli" \
    "https://github.com/openfaas/faas-cli/releases/download/${version}/faas-cli"
chmod +x "${prefix}${target}/bin/faas-cli"
EOF