#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:603df81cedf0e7d932932147512697e3d846a73733f9329e77910d38c8c846be
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/slirp4netns" \
    "https://github.com/rootless-containers/slirp4netns/releases/download/v${version}/slirp4netns-${arch}"
chmod +x "${prefix}${target}/bin/slirp4netns"
curl --silent --location --fail --output "${prefix}${target}/share/man/man1/slirp4netns.1" \
    "https://github.com/rootless-containers/slirp4netns/raw/v${version}/slirp4netns.1"
EOF