#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:8189cf0a45306137d245c98e212f7c29379f3d11ca4cc549c1b97aadcd813846
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/slirp4netns" \
    "https://github.com/rootless-containers/slirp4netns/releases/download/v${version}/slirp4netns-${arch}"
chmod +x "${prefix}${target}/bin/slirp4netns"
curl --silent --location --fail --output "${prefix}${target}/share/man/man1/slirp4netns.1" \
    "https://github.com/rootless-containers/slirp4netns/raw/v${version}/slirp4netns.1"
EOF