#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-github-release-asset "artifacthub/hub" "v${version}" "ah_${version}_linux_${alt_arch}.tar.gz"
curl --silent --location --fail "https://github.com/artifacthub/hub/releases/download/v${version}/ah_${version}_linux_${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}${target}/bin/" --no-same-owner \
    ah
EOF