#syntax=docker/dockerfile:1.4.3

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --output "${prefix}${target}/bin/docker-credential-ecr-login" \
    "https://amazon-ecr-credential-helper-releases.s3.us-east-2.amazonaws.com/${version}/linux-${alt_arch}/docker-credential-ecr-login"
chmod +x "${prefix}${target}/bin/docker-credential-ecr-login"
EOF