#syntax=docker/dockerfile:1.4.3

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/ghostunnel" \
    "https://github.com/ghostunnel/ghostunnel/releases/download/v${version}/ghostunnel-linux-amd64"
chmod +x "${prefix}${target}/bin/ghostunnel"
EOF