#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-github-release-asset "ghostunnel/ghostunnel" "v${version}" "ghostunnel-linux-${alt_arch}"
curl --silent --location --fail --output "${prefix}${target}/bin/ghostunnel" \
    "https://github.com/ghostunnel/ghostunnel/releases/download/v${version}/ghostunnel-linux-${alt_arch}"
chmod +x "${prefix}${target}/bin/ghostunnel"
EOF