#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:8189cf0a45306137d245c98e212f7c29379f3d11ca4cc549c1b97aadcd813846

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/libexec/docker/cli-plugins/docker-compose" \
    "https://github.com/docker/compose/releases/download/v${version}/docker-compose-linux-${arch}"
chmod +x "${prefix}${target}/libexec/docker/cli-plugins/docker-compose"
EOF