#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/lazytrivy" \
    "https://github.com/owenrumney/lazytrivy/releases/download/v${version}/lazytrivy-linux-${alt_arch}"
chmod +x "${prefix}${target}/bin/lazytrivy"
EOF