#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-github-release-asset "wader/fq" "${version}" "fq_${version}_linux_${arch}.tar.gz"
curl --silent --location --fail "https://github.com/wader/fq/releases/download/v${version}/fq_${version}_linux_${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}${target}/bin/" --no-same-owner
EOF