#syntax=docker/dockerfile:1.5.2

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
curl --silent --location --fail "https://github.com/bytecodealliance/wasmtime/releases/download/v${version}/wasmtime-v${version}-${arch}-linux.tar.xz" \
| tar --extract --xz --directory="${prefix}${target}/bin/" --strip-components=1 --no-same-owner \
    "./wasmtime-v${version}-${arch}-linux/wasmtime"
EOF