#syntax=docker/dockerfile:1.4.3

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail "https://github.com/agrinman/tunnelto/releases/download/${version}/tunnelto-linux.tar.gz" \
| tar --extract --gzip --directory="${prefix}${target}/bin/" --no-same-owner
EOF