#syntax=docker/dockerfile:1.5.1

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/tini" \
    "https://github.com/krallin/tini/releases/download/v${version}/tini-${alt_arch}"
chmod +x "${prefix}${target}/bin/tini"
EOF