#syntax=docker/dockerfile:1.6.0

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
check-github-release-asset "CycloneDX/cyclonedx-cli" "v${version}" "cyclonedx-linux-x64"
curl --silent --location --fail --output "${prefix}${target}/bin/cyclonedx-cli" \
    "https://github.com/CycloneDX/cyclonedx-cli/releases/download/v${version}/cyclonedx-linux-x64"
chmod +x "${prefix}${target}/bin/cyclonedx-cli"
EOF