#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-github-release-asset "ivanilves/lstags" "v${version}" "lstags-linux-${alt_arch}"
curl --silent --location --fail "https://github.com/ivanilves/lstags/releases/download/v${version}/lstags-linux-v${version}.tar.gz" \
| tar --extract --gzip --directory="${prefix}${target}/bin/" --no-same-owner
EOF