#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/has" \
    "https://github.com/kdabir/has/raw/v${version}/has"
chmod +x "${prefix}${target}/bin/has"
EOF