#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-github-release-asset "moncho/dry" "v${version}" "dry-linux-${alt_arch}"
curl --silent --location --fail --output "${prefix}${target}/bin/dry" \
    "https://github.com/moncho/dry/releases/download/v${version}/dry-linux-${alt_arch}"
chmod +x "${prefix}${target}/bin/dry"
EOF