#syntax=docker/dockerfile:1.4.3

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/dry" \
    "https://github.com/moncho/dry/releases/download/v${version}/dry-linux-${alt_arch}"
chmod +x "${prefix}${target}/bin/dry"
EOF