#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-github-release-asset "imsnif/bandwhich" "v${version}" "bandwhich-v${version}-${arch}-unknown-linux-musl.tar.gz"
curl --silent --location --fail "https://github.com/imsnif/bandwhich/releases/download/${version}/bandwhich-v${version}-${arch}-unknown-linux-musl.tar.gz" \
| tar --extract --gzip --directory="${prefix}${target}/bin/" --no-same-owner
EOF