#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:603df81cedf0e7d932932147512697e3d846a73733f9329e77910d38c8c846be
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

# tarball
RUN <<EOF
curl --silent --location --fail "https://github.com/little-angry-clouds/kubectl-ssh-proxy/releases/download/${version}/kubectl-ssh-proxy-linux-amd64.tar.gz" \
| tar --extract --gzip --directory="${prefix}${target}" --no-same-owner
mv "${prefix}${target}/bin/kubectl-ssh_proxy-linux-amd64" "${prefix}${target}/bin/kubectl-ssh_proxy"
mv "${prefix}${target}/bin/kube-ssh-proxy-ssh-bin-linux-amd64" "${prefix}${target}/bin/kube-ssh-proxy-ssh-bin"
EOF