#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:8189cf0a45306137d245c98e212f7c29379f3d11ca4cc549c1b97aadcd813846
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
mkdir -p "${prefix}${target}/share/htmx"
curl --silent --location --fail --output "${prefix}${target}/share/htmx/htmx.min.js" \
    "https://github.com/bigskysoftware/htmx/releases/download/v${version}/htmx.min.js"
EOF