#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:603df81cedf0e7d932932147512697e3d846a73733f9329e77910d38c8c846be
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
mkdir -p "${prefix}${target}/share/htmx"
curl --silent --location --fail --output "${prefix}${target}/share/htmx/htmx.min.js" \
    "https://github.com/bigskysoftware/htmx/releases/download/v${version}/htmx.min.js"
EOF