#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:8189cf0a45306137d245c98e212f7c29379f3d11ca4cc549c1b97aadcd813846
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/libexec/docker/cli-plugins/docker-buildx" \
    "https://github.com/docker/buildx/releases/download/v${version}/buildx-v${version}.linux-${alt_arch}"
chmod +x "${prefix}${target}/libexec/docker/cli-plugins/docker-buildx"
"${prefix}${target}/libexec/docker/cli-plugins/docker-buildx" completion bash | sed "s|${prefix}||g" >"${prefix}${target}/share/bash-completion/completions/docker-buildx"
"${prefix}${target}/libexec/docker/cli-plugins/docker-buildx" completion fish | sed "s|${prefix}||g" >"${prefix}${target}/share/fish/vendor_completions.d/docker-buildx.fish"
"${prefix}${target}/libexec/docker/cli-plugins/docker-buildx" completion zsh  | sed "s|${prefix}||g" >"${prefix}${target}/share/zsh/vendor-completions/_docker-buildx"
EOF