#syntax=docker/dockerfile:1.5.1

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/sops" \
    "https://github.com/mozilla/sops/releases/download/v${version}/sops-v${version}.linux"
chmod +x "${prefix}${target}/bin/sops"
EOF