#syntax=docker/dockerfile:1.5.1

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/wsl-open" \
    "https://github.com/4U6U57/wsl-open/raw/v${version}/wsl-open.sh"
chmod +x "${prefix}${target}/bin/wsl-open"

curl --silent --location --fail --output "${prefix}${target}/share/man/man1/wsl-open.1" \
    "https://github.com/4U6U57/wsl-open/raw/v${version}/wsl-open.1"
EOF