#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-github-release-asset "wfxr/forgit" "${version}" "forgit.plugin.zsh"
curl --silent --location --fail --output "${prefix}${target}/etc/profile.d/forgit.sh" \
    "https://github.com/wfxr/forgit/raw/${version}/forgit.plugin.zsh"
EOF