#syntax=docker/dockerfile:1.5.2

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/etc/profile.d/forgit.sh" \
    "https://github.com/wfxr/forgit/raw/${version}/forgit.plugin.zsh"
EOF