#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/kgctl" \
    "https://github.com/squat/kilo/releases/download/${version}/kgctl-linux-${alt_arch}"
chmod +x "${prefix}${target}/bin/kgctl"
EOF