#syntax=docker/dockerfile:1.4.3

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --output "${prefix}${target}/bin/footloose" \
    "https://github.com/weaveworks/footloose/releases/download/${version}/footloose-${version}-linux-${arch}"
chmod +x "${prefix}${target}/bin/footloose"
EOF