#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:8189cf0a45306137d245c98e212f7c29379f3d11ca4cc549c1b97aadcd813846
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail "https://github.com/argoproj/argo-workflows/releases/download/v${version}/argo-linux-${alt_arch}.gz" \
| gunzip \
>"${prefix}${target}/bin/argo"
chmod +x "${prefix}${target}/bin/argo"
"${prefix}${target}/bin/argo" completion bash >"${prefix}${target}/share/bash-completion/completions/argo"
"${prefix}${target}/bin/argo" completion zsh >"${prefix}${target}/share/zsh/vendor-completions/_argo"
EOF