#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:603df81cedf0e7d932932147512697e3d846a73733f9329e77910d38c8c846be
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail "https://github.com/argoproj/argo-workflows/releases/download/v${version}/argo-linux-${alt_arch}.gz" \
| gunzip \
>"${prefix}${target}/bin/argo"
chmod +x "${prefix}${target}/bin/argo"
"${prefix}${target}/bin/argo" completion bash >"${prefix}${target}/share/bash-completion/completions/argo"
"${prefix}${target}/bin/argo" completion zsh >"${prefix}${target}/share/zsh/vendor-completions/_argo"
EOF