name: argo
version: 3.4.3
check: ${binary} version | grep ^argo | cut -d' ' -f2 | tr -d v
tags:
- tag1
- tag2
homepage: https://github.com/argoproj/argo-workflows
description: Workflow engine for Kubernetes
renovate:
  datasource: github-releases
  package: argoproj/argo-workflows
  extractVersion: ^v(?<version>.+?)$