name: argo
version: "3.4.7"
check: ${binary} version | grep ^argo | cut -d' ' -f2 | tr -d v
tags:
- type/cli
- kubernetes
- org/cncf
- cicd
- lang/go
homepage: https://github.com/argoproj/argo-workflows
description: Workflow engine for Kubernetes
renovate:
  datasource: github-releases
  package: argoproj/argo-workflows
  extractVersion: ^v(?<version>.+?)$