#syntax=docker/dockerfile:1.4.3

ARG ref=main

FROM golang:1.19.4@sha256:941582ed5a1189ce2c8cf6a806cfb8f5924694e1f58856869f98364315de6231 AS build
WORKDIR /go/src/github.com/flatcar/container-linux-config-transpiler
ARG name
ARG version
RUN <<EOF
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/flatcar/container-linux-config-transpiler .
make
cp bin/ct /usr/local/bin/
EOF

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
COPY --from=build /usr/local/bin/ct ${prefix}${target}/bin/