#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:603df81cedf0e7d932932147512697e3d846a73733f9329e77910d38c8c846be

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
url="https://github.com/jeremylong/DependencyCheck/releases/download/v${version}/dependency-check-${version}-release.zip"
filename="$(basename "${url}")"
curl --silent --location --fail --remote-name "${url}"
unzip -q -o -d "${prefix}/opt" "${filename}"
ln --symbolic --relative --force /opt/dependency-check/bin/dependency-check.sh "${prefix}${target}/bin/dependency-check.sh"
mv "${prefix}/opt/dependency-check/bin/completion-for-dependency-check.sh" "${prefix}${target}/share/bash-completion/completions/dependency-check.sh"
EOF