#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:8189cf0a45306137d245c98e212f7c29379f3d11ca4cc549c1b97aadcd813846

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
url="https://github.com/jeremylong/DependencyCheck/releases/download/v${version}/dependency-check-${version}-release.zip"
filename="$(basename "${url}")"
curl --silent --location --fail --remote-name "${url}"
unzip -q -o -d "${prefix}/opt" "${filename}"
ln --symbolic --relative --force /opt/dependency-check/bin/dependency-check.sh "${prefix}${target}/bin/dependency-check.sh"
mv "${prefix}/opt/dependency-check/bin/completion-for-dependency-check.sh" "${prefix}${target}/share/bash-completion/completions/dependency-check.sh"
EOF