#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-github-release-asset "jeremylong/DependencyCheck" "v${version}" "dependency-check-${version}-release.zip"
url="https://github.com/jeremylong/DependencyCheck/releases/download/v${version}/dependency-check-${version}-release.zip"
filename="$(basename "${url}")"
curl --silent --location --fail --remote-name "${url}"
unzip -q -o -d "${prefix}${target}/opt" "${filename}"
ln --symbolic --relative --force "${target}/opt/dependency-check/bin/dependency-check.sh" "${prefix}${target}/bin/dependency-check.sh"
mv "${prefix}${target}/opt/dependency-check/bin/completion-for-dependency-check.sh" "${prefix}${target}/share/bash-completion/completions/dependency-check.sh"
EOF