#syntax=docker/dockerfile:1.4.3

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/jabba:${ref} AS jabba

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
COPY --from=jabba / /
ARG name
ARG version
RUN <<EOF
jabba install --output "${prefix}/opt/openjdk/" openjdk@1.${version}
cd "${prefix}/opt/openjdk/bin"
find . -type f -executable \
| while read -r BINARY; do
    ln -sf "/opt/openjdk/bin/${BINARY:2}" "${prefix}${target}/bin/${BINARY:2}"
done
EOF