#syntax=docker/dockerfile:1.5.1

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
# agent
RUN <<EOF
url="https://github.com/grafana/agent/releases/download/v${version}/grafana-agent-linux-${alt_arch}.zip"
filename="$(basename "${url}")"
curl --silent --location --fail --remote-name "${url}"
unzip -q -o -d "${prefix}${target}/bin" "${filename}"
ls -l "${prefix}${target}/bin"
mv "${prefix}${target}/bin/grafana-agent-linux-${alt_arch}" "${prefix}${target}/bin/grafana-agent"
EOF
# agentctl
RUN <<EOF
url="https://github.com/grafana/agent/releases/download/v${version}/grafana-agentctl-linux-${alt_arch}.zip"
filename="$(basename "${url}")"
curl --silent --location --fail --remote-name "${url}"
unzip -q -o -d "${prefix}${target}/bin" "${filename}"
mv "${prefix}${target}/bin/grafana-agentctl-linux-${alt_arch}" "${prefix}${target}/bin/grafana-agentctl"
"${prefix}${target}/bin/grafana-agentctl" completion bash >"${prefix}${target}/share/bash-completion/completions/grafana-agentctl"
"${prefix}${target}/bin/grafana-agentctl" completion fish >"${prefix}${target}/share/fish/vendor_completions.d/grafana-agentctl.fish"
"${prefix}${target}/bin/grafana-agentctl" completion zsh >"${prefix}${target}/share/zsh/vendor-completions/_grafana-agentctl"
EOF