#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:603df81cedf0e7d932932147512697e3d846a73733f9329e77910d38c8c846be
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/kn" \
    "https://github.com/knative/client/releases/download/knative-v${version}/kn-linux-${alt_arch}"
chmod +x "${prefix}${target}/bin/kn"
"${prefix}${target}/bin/kn" completion bash >"${prefix}${target}/share/bash-completion/completions/kn"
"${prefix}${target}/bin/kn" completion zsh >"${prefix}${target}/share/zsh/vendor-completions/_kn"
EOF