#syntax=docker/dockerfile:1.5.1

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/kubeletctl" \
    "https://github.com/cyberark/kubeletctl/releases/download/v${version}/kubeletctl_linux_${alt_arch}"
chmod +x "${prefix}${target}/bin/kubeletctl"
EOF