#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:8189cf0a45306137d245c98e212f7c29379f3d11ca4cc549c1b97aadcd813846

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/minio" \
    "https://dl.min.io/server/minio/release/linux-amd64/minio.RELEASE.${version}"
chmod +x "${prefix}${target}/bin/minio"
EOF