#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:8189cf0a45306137d245c98e212f7c29379f3d11ca4cc549c1b97aadcd813846
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/switcher" \
    "https://github.com/danielfoehrKn/kubeswitch/releases/download/${version}/switcher_linux_${alt_arch}"
chmod +x "${prefix}${target}/bin/switcher"

curl --silent --location --fail --output "${prefix}${target}/bin/switch.sh" \
    "https://github.com/danielfoehrKn/kubeswitch/releases/download/${version}/switch.sh"
chmod +x "${prefix}${target}/bin/switch.sh"

curl --silent --location --fail --output "${prefix}${target}/share/bash-completion/completions/${name}" \
    "https://github.com/danielfoehrKn/kubeswitch/raw/${version}/scripts/_switch.bash"
EOF