#syntax=docker/dockerfile:1.5.1

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/firectl" \
    "https://github.com/firecracker-microvm/firectl/releases/download/v${version}/firectl-v${version}"
chmod +x "${prefix}${target}/bin/firectl"
EOF