#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-github-release-asset "fugue/fregot" "v${version}" "fregot-v${version}-linux.tar.gz"
curl --silent --location --fail "https://github.com/fugue/fregot/releases/download/v${version}/fregot-v${version}-linux.tar.gz" \
| tar --extract --gzip --directory="${prefix}${target}/bin/" --no-same-owner
EOF