#syntax=docker/dockerfile:1.5.2

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
mkdir -p "${prefix}/opt"
curl --silent --location --fail "https://github.com/tinygo-org/tinygo/releases/download/v${version}/tinygo${version}.linux-${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/opt/" --no-same-owner
ln --symbolic --relative --force "${prefix}/opt/tinygo/bin/tinygo" "${prefix}${target}/bin/tinygo"
EOF