#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-github-release-asset "opencontainers/umoci" "v${version}" "umoci.${alt_arch}"
curl --silent --location --fail --output "${prefix}${target}/bin/umoci" \
    "https://github.com/opencontainers/umoci/releases/download/v${version}/umoci.${alt_arch}"
chmod +x "${prefix}${target}/bin/umoci"
EOF