#syntax=docker/dockerfile:1.4.3

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --output "${prefix}${target}/bin/umoci" \
    "https://github.com/opencontainers/umoci/releases/download/v${version}/umoci.${alt_arch}"
chmod +x "${prefix}${target}/bin/umoci"
EOF