#syntax=docker/dockerfile:1.4.3

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/python:${ref} AS python

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
COPY --link --from=python / /
ENV PIPX_HOME=${prefix}${target}/libexec/pipx \
    PIPX_BIN_DIR=${prefix}${target}/bin
WORKDIR /tmp/pass-audit
ARG name
ARG version
RUN <<EOF
curl --silent --location --fail "https://github.com/roddhjav/pass-audit/releases/download/v${version}/pass-audit-${version}.tar.gz" \
| tar --extract --gzip --strip-components=1 --no-same-owner
mkdir -p "${prefix}${target}/usr/lib/password-store/extensions/"
cp audit.bash "${prefix}${target}/usr/lib/password-store/extensions/"
cp share/man/man1/pass-audit.1 "${prefix}${target}/share/man/man1/"
cp share/bash-completion/completions/pass-audit "${prefix}${target}/share/bash-completion/completions/"
cp share/zsh/site-functions/_pass-audit "${prefix}${target}/share/zsh/vendor-completions/"
EOF