#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-github-release-asset "omrikiei/ktunnel" "v${version}" "ktunnel_${version}_Linux_x86_64.tar.gz"
curl --silent --location --fail "https://github.com/omrikiei/ktunnel/releases/download/v${version}/ktunnel_${version}_Linux_x86_64.tar.gz" \
| tar --extract --gzip --directory="${prefix}${target}/bin/" --no-same-owner \
    ktunnel
EOF