FROM alpine:3.15@sha256:3c4222bc5d16ab768ce961fec6fb14150586c84437840a5f9e7086445f60a015
RUN apk add --update-cache --no-cache \
        bash \
        curl \
        ca-certificates \
        procps \
        iptables \
        shadow \
        openrc \
        git \
        tzdata \
        libc6-compat \
        libbsd \
        gcompat \
        libgcc \
        unzip \
        ncurses \
        jq \
        tar \
 && mkdir -p /run/openrc \
 && touch /run/openrc/softlevel
COPY env/run.sh /
COPY docker-setup.sh /usr/local/bin/docker-setup
COPY tools.json /var/cache/docker-setup/
RUN chmod +x /usr/local/bin/docker-setup