#syntax=docker/dockerfile:1.5.1

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/dumb-init" \
    "https://github.com/Yelp/dumb-init/releases/download/v${version}/dumb-init_${version}_${arch}"
chmod +x "${prefix}${target}/bin/dumb-init"
EOF