#syntax=docker/dockerfile:1.4.3

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/docker-compose-switch" \
    "https://github.com/docker/compose-switch/releases/download/v${version}/docker-compose-linux-${alt_arch}"
chmod +x "${prefix}${target}/bin/docker-compose-switch"
EOF