#syntax=docker/dockerfile:1.5.2

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/shiv" \
    "https://github.com/linkedin/shiv/releases/download/${version}/shiv"
chmod +x "${prefix}${target}/bin/shiv"
EOF