#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-github-release-asset "charmbracelet/glow" "v${version}" "glow_Linux_${arch}.tar.gz"
curl --silent --location --fail "https://github.com/charmbracelet/glow/releases/download/v${version}/glow_Linux_${arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}${target}/bin" --no-same-owner \
    glow
EOF