#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:603df81cedf0e7d932932147512697e3d846a73733f9329e77910d38c8c846be
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/slsa-verifier" \
    "https://github.com/slsa-framework/slsa-verifier/releases/download/v${version}/slsa-verifier-linux-${alt_arch}"
chmod +x "${prefix}${target}/bin/slsa-verifier"
EOF