#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-github-release-asset "Mic92/cntr" "${version}" "cntr-bin-${version}-${arch}-unknown-linux-musl"
curl --silent --location --fail --output "${prefix}${target}/bin/cntr" \
    "https://github.com/Mic92/cntr/releases/download/${version}/cntr-bin-${version}-${arch}-unknown-linux-musl"
chmod +x "${prefix}${target}/bin/cntr"
EOF