#syntax=docker/dockerfile:1.5.2

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/git-filter-repo" \
    "https://github.com/newren/git-filter-repo/raw/v${version}/git-filter-repo"
chmod +x "${prefix}${target}/bin/git-filter-repo"
EOF