#syntax=docker/dockerfile:1.5.1

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/shdotenv" \
    "https://github.com/ko1nksm/shdotenv/releases/download/v${version}/shdotenv"
chmod +x "${prefix}${target}/bin/shdotenv"
EOF