#syntax=docker/dockerfile:1.5.1

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/ansi" \
    "https://github.com/fidian/ansi/raw/${version}/ansi"
chmod +x "${prefix}${target}/bin/ansi"
EOF