#syntax=docker/dockerfile:1.4.3

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
url="https://github.com/andreazorzetto/yh/releases/download/v${version}/yh-linux-amd64.zip"
filename="$(basename "${url}")"
echo "Downloading ${filename} from ${url}."
curl --silent --location --remote-name "${url}"
unzip -q -o -d "${prefix}${target}/bin" "${filename}"
EOF