#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:603df81cedf0e7d932932147512697e3d846a73733f9329e77910d38c8c846be
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

COPY k3s.service ${prefix}/etc/systemd/system/

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/k3s" \
    "https://github.com/k3s-io/k3s/releases/download/v${version}/k3s"
chmod +x "${prefix}${target}/bin/k3s"
"${prefix}${target}/bin/k3s" completion bash >"${prefix}${target}/share/bash-completion/completions/k3s"
"${prefix}${target}/bin/k3s" completion zsh >"${prefix}${target}/share/zsh/vendor-completions/_k3s"
EOF