#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:8189cf0a45306137d245c98e212f7c29379f3d11ca4cc549c1b97aadcd813846

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
curl --silent --location --fail "https://github.com/indygreg/python-build-standalone/releases/download/${version}/cpython-3.10.9+${version}-x86_64-unknown-linux-musl-install_only.tar.gz" \
| tar --extract --gzip --directory="${prefix}${target}/" --strip-components=1 --no-same-owner
EOF