#syntax=docker/dockerfile:1.5.1

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
curl --silent --location --fail "https://github.com/indygreg/python-build-standalone/releases/download/${version}/cpython-3.10.9+${version}-x86_64-unknown-linux-musl-install_only.tar.gz" \
| tar --extract --gzip --directory="${prefix}${target}/" --strip-components=1 --no-same-owner
EOF