#syntax=docker/dockerfile:1.5.1

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/libexec/docker/cli-plugins/docker-scan" \
    "https://github.com/docker/scan-cli-plugin/releases/download/v${version}/docker-scan_linux_${alt_arch}"
chmod +x "${prefix}${target}/libexec/docker/cli-plugins/docker-scan"
EOF