#syntax=docker/dockerfile:1.4.3

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/libexec/docker/cli-plugins/docker-scan" \
    "https://github.com/docker/scan-cli-plugin/releases/download/v${version}/docker-scan_linux_${alt_arch}"
chmod +x "${prefix}${target}/libexec/docker/cli-plugins/docker-scan"
"${prefix}${target}/libexec/docker/cli-plugins/docker-scan" completion bash >"${prefix}${target}/share/bash-completion/completions/docker-scan"
"${prefix}${target}/libexec/docker/cli-plugins/docker-scan" completion fish >"${prefix}${target}/share/fish/vendor_completions.d/docker-scan.fish"
"${prefix}${target}/libexec/docker/cli-plugins/docker-scan" completion zsh >"${prefix}${target}/share/zsh/vendor-completions/_docker-scan"
EOF