#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:8189cf0a45306137d245c98e212f7c29379f3d11ca4cc549c1b97aadcd813846
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail "https://github.com/sysdiglabs/kube-psp-advisor/releases/download/v${version}/kube-psp-advisor_v${version}_linux_amd64.tar.gz" \
| tar --extract --gzip --directory="${prefix}${target}/bin/" --no-same-owner \
    kubectl-advise-psp
EOF