#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/go:${ref} AS go

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
COPY --link --from=go / /
WORKDIR /go/src/github.com/liamg/tml
RUN <<EOF
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/liamg/tml .
go build -o "${prefix}${target}/bin/tml"  -ldflags "-X github.com/liamg/tml/version.Version=${version}" ./tml
EOF