#syntax=docker/dockerfile:1.4.3

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version

RUN <<EOF
curl --silent --location --fail "https://github.com/docker/index-cli-plugin/releases/download/v0.0.28/docker-index_0.0.28_linux_amd64.tar.gz" \
| tar --extract --gzip --directory="${prefix}${target}/libexec/docker/cli-plugins" --no-same-owner \
    docker-index
"${prefix}${target}/libexec/docker/cli-plugins/docker-index" completion bash >"${prefix}${target}/share/bash-completion/completions/docker-index"
"${prefix}${target}/libexec/docker/cli-plugins/docker-index" completion fish >"${prefix}${target}/share/fish/vendor_completions.d/docker-index.fish"
"${prefix}${target}/libexec/docker/cli-plugins/docker-index" completion zsh >"${prefix}${target}/share/zsh/vendor-completions/_docker-index"
EOF