#syntax=docker/dockerfile:1.5.1

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
curl --silent --location --fail "https://github.com/docker/index-cli-plugin/releases/download/v${version}/docker-index_${version}_linux_${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}${target}/libexec/docker/cli-plugins" --no-same-owner \
    docker-index
"${prefix}${target}/libexec/docker/cli-plugins/docker-index" completion bash | sed "s|${prefix}||g" >"${prefix}${target}/share/bash-completion/completions/docker-index"
"${prefix}${target}/libexec/docker/cli-plugins/docker-index" completion fish | sed "s|${prefix}||g" >"${prefix}${target}/share/fish/vendor_completions.d/docker-index.fish"
"${prefix}${target}/libexec/docker/cli-plugins/docker-index" completion zsh  | sed "s|${prefix}||g" >"${prefix}${target}/share/zsh/vendor-completions/_docker-index"
EOF