#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-github-release-asset "EnvCLI/EnvCLI" "v${version}" "linux_${alt_arch}"
curl --silent --location --fail --output "${prefix}${target}/bin/envcli" \
    "https://github.com/EnvCLI/EnvCLI/releases/download/v${version}/linux_${alt_arch}"
chmod +x "${prefix}${target}/bin/envcli"
EOF