#syntax=docker/dockerfile:1.4.3

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail "https://github.com/docker/base-cli-plugin/releases/download/v${version}/base-cli-plugin_${version}_linux_${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}${target}/libexec/docker/cli-plugins" --no-same-owner \
    docker-base
"${prefix}${target}/libexec/docker/cli-plugins/docker-base" completion bash >"${prefix}${target}/share/bash-completion/completions/docker-base"
"${prefix}${target}/libexec/docker/cli-plugins/docker-base" completion fish >"${prefix}${target}/share/fish/vendor_completions.d/docker-base.fish"
"${prefix}${target}/libexec/docker/cli-plugins/docker-base" completion zsh >"${prefix}${target}/share/zsh/vendor-completions/_docker-base"
EOF