#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-github-release-asset "carvel-dev/imgpkg" "v${version}" "imgpkg-linux-${alt_arch}"
curl --silent --location --fail --output "${prefix}${target}/bin/imgpkg" \
    "https://github.com/carvel-dev/imgpkg/releases/download/v${version}/imgpkg-linux-${alt_arch}"
chmod +x "${prefix}${target}/bin/imgpkg"
EOF