#syntax=docker/dockerfile:1.4.3

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --output "${prefix}${target}/bin/imgpkg" \
    "https://github.com/vmware-tanzu/carvel-imgpkg/releases/download/v${version}/imgpkg-linux-${alt_arch}"
chmod +x "${prefix}${target}/bin/imgpkg"
EOF