#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:8189cf0a45306137d245c98e212f7c29379f3d11ca4cc549c1b97aadcd813846

FROM ghcr.io/nicholasdille/docker-setup/python:${ref} AS python
FROM ghcr.io/nicholasdille/docker-setup/shiv:${ref} AS shiv

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
COPY --link --from=python / /
COPY --link --from=shiv / /
ARG name
ARG version
RUN <<EOF
shiv --output-file "${prefix}${target}/bin/it-depends" --console-script it-depends "it-depends==${version}"
EOF