#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/python:${ref} AS python
FROM ghcr.io/nicholasdille/docker-setup/shiv:${ref} AS shiv

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
COPY --link --from=python / /
COPY --link --from=shiv / /
ARG name
ARG version
RUN <<EOF
shiv --output-file "${prefix}${target}/bin/it-depends" --console-script it-depends "it-depends==${version}"
EOF