#syntax=docker/dockerfile:1.5.2

ARG ref=main@sha256:8189cf0a45306137d245c98e212f7c29379f3d11ca4cc549c1b97aadcd813846

FROM --platform=amd64 ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
curl --silent --location --fail "https://github.com/parca-dev/parca-agent/releases/download/v${version}/parca-agent_Linux_${arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}${target}/bin/" --no-same-owner \
    parca-agent
EOF

FROM --platform=arm64 ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
printenv
set -x
curl --silent --location --fail "https://github.com/parca-dev/parca-agent/releases/download/v${version}/parca-agent_Linux_${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}${target}/bin/" --no-same-owner \
    parca-agent
EOF