#syntax=docker/dockerfile:1.4.3

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}${target}/bin/lectl" \
    "https://github.com/sahsanu/lectl/raw/v${version}/lectl"
chmod +x "${prefix}${target}/bin/lectl"
EOF