name: gitlab-ci-pipelines-exporter
version: "0.5.5"
check: ${binary} --version | cut -d' ' -f3
platforms:
- linux/amd64
- linux/arm64
tags:
- category/development
- lang/go
- type/cli
homepage: https://github.com/mvisonneau/gitlab-ci-pipelines-exporter
description: Prometheus / OpenMetrics exporter for GitLab CI pipelines insights
renovate:
  datasource: github-releases
  package: mvisonneau/gitlab-ci-pipelines-exporter
  extractVersion: ^v(?<version>.+?)$
  priority: medium