#syntax=docker/dockerfile:1.4.3

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --output "${prefix}${target}/bin/sshocker" \
    "https://github.com/lima-vm/sshocker/releases/download/v${version}/sshocker-Linux-${arch}"
chmod +x "${prefix}${target}/bin/sshocker"
EOF