#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-github-release-asset "lima-vm/sshocker" "${version}" "sshocker-Linux-${arch}"
curl --silent --location --fail --output "${prefix}${target}/bin/sshocker" \
    "https://github.com/lima-vm/sshocker/releases/download/v${version}/sshocker-Linux-${arch}"
chmod +x "${prefix}${target}/bin/sshocker"
EOF