#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-github-release-asset "pan-net-security/kcount" "${version}" "kcount_${version}_Linux_x86_64.tar.gz"
curl --silent --location --fail "https://github.com/pan-net-security/kcount/releases/download/v${version}/kcount_${version}_Linux_x86_64.tar.gz" \
| tar --extract --gzip --directory="${prefix}${target}/bin/" --no-same-owner \
    kcount
EOF