#syntax=docker/dockerfile:1.4.3

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --output "${prefix}${target}/bin/kubectl-crossplane" \
    "https://releases.crossplane.io/stable/v${version}/bin/linux_${alt_arch}/crank"
chmod +x "${prefix}${target}/bin/kubectl-crossplane"
EOF