#syntax=docker/dockerfile:1.4.3

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location --output "${prefix}${target}/bin/neofetch" \
    "https://github.com/dylanaraps/neofetch/raw/${version}/neofetch"
chmod +x "${prefix}${target}/bin/neofetch"
curl --silent --location --output "${prefix}${target}/share/man/man1/neofetch.1" \
    "https://github.com/dylanaraps/neofetch/raw/${version}/neofetch.1"
EOF