#syntax=docker/dockerfile:1.4.3

ARG ref=main
FROM ghcr.io/nicholasdille/docker-setup/base:${ref} AS prepare

ARG name
ARG version

RUN <<EOF
curl --silent --location "https://github.com/norouter/norouter/releases/download/v${version}/norouter-Linux-${arch}.tgz" \
| tar --extract --gzip --directory="${prefix}${target}/bin" --no-same-owner \
    norouter
EOF