name: Build site

on:
  push:
    branches:
      - "main"
    paths:
      - "tools/**"
      - "scripts/gh-pages.sh"
      - "make/site.mk"
      - ".github/workflows/pages.yml"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  build:
    name: Build
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create metadata
        run: |
          make metadata.json

      - name: Install hugo
        run: |
          make site-prerequisites

      - name: Create pages
        run: |
          make -j4 pages

      - name: Create site
        run: |
          make site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./site/public

  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs:
    - build
    runs-on: ubuntu-22.04
    concurrency:
      group: pages
      cancel-in-progress: true
    steps:

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2