name: Build site

on:
  push:
    branches:
      - "main"
    paths:
      - "tools/**"
      - "scripts/gh-pages.sh"
      - "make/site.mk"
      - ".github/workflows/pages.yml"

jobs:

  build:
    name: Build
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry as ${{ secrets.BOT_USERNAME }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: nicholasdille
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Create pages and generate site
        run: |
          make site

      - name: Package site
        run: |
          cd site/public
          tar -czf ../public.tar.gz .

      - name: Store artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: site
          path: site/public.tar.gz

  deploy:
    name: Deploy
    needs:
    - build
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
      
      - name: Fetch artifact
        uses: actions/download-artifact@v3
        with:
          name: site

      - name: Unpack site
        run: |
          find . -type f
          tar -xzf public.tar.gz

      - name: Commit site
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: gh-pages
          create_branch: false
          commit_message: "Updated GitHub Pages automatically"