name: Build and push

on:
  push:
    branches:
    - "main"
    paths:
    - "tools/**"
    - "Makefile"
    - ".github/workflows/push.yml"
  workflow_dispatch:

jobs:

  test:
    name: Build and push
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install docker-setup
      run: |
        mkdir -p helper/usr/local/bin
        curl --url "https://github.com/nicholasdille/docker-setup/releases/latest/download/docker-setup" \
            --silent \
            --location \
            --fail \
            --output helper/usr/local/bin/docker-setup
        chmod +x helper/usr/local/bin/docker-setup

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: nicholasdille
        password: ${{ secrets.PACKAGES_TOKEN }}

    - name: Push
      env:
        DOCKER_BUILDKIT: 1
        AUTHOR: ${{ github.event.commits[0].author.name }}
      run: |
        echo "### Running for commit by author: ${AUTHOR}"

        mkdir -p helper helper/var/cache helper/var/lib
        helper/usr/local/bin/docker-setup --prefix "$PWD/helper" update
        helper/usr/local/bin/docker-setup --prefix "$PWD/helper" install gojq regclient
        # TODO: Remove workaround for gojq once post_install is implemented in go-based CLI
        ln -sfr helper/usr/local/bin/gojq helper/usr/local/bin/jq

        echo "### Fetching config for metadata"
        OLD_COMMIT_SHA="$(
            helper/usr/local/bin/jq \
                --raw-output \
                '.revision' \
                helper/var/cache/docker-setup/metadata.json
        )"

        echo "### Fetching changed tools for ${OLD_COMMIT_SHA}..${GITHUB_SHA}"
        git log --pretty=format: --name-only ${OLD_COMMIT_SHA}..${GITHUB_SHA} \
        | sort \
        | grep -E "^tools/[^/]+/" \
        | cut -d/ -f2 \
        | uniq \
        | xargs
        CHANGED_TOOLS="$(
            git log --pretty=format: --name-only ${OLD_COMMIT_SHA}..${GITHUB_SHA} \
            | sort \
            | grep -E "^tools/[^/]+/" \
            | cut -d/ -f2 \
            | uniq \
            | xargs
        )"

        if test -z "${CHANGED_TOOLS}"; then
            echo "### No tools to make (${CHANGED_TOOLS})"
            echo "### git log:"
            git log --name-only ${OLD_COMMIT_SHA}..${GITHUB_SHA}
            exit
        fi

        for TOOL in ${CHANGED_TOOLS}; do
            if regctl tag ls "ghcr.io/nicholasdille/docker-setup/${TOOL}" | grep -q test; then
                make "${TOOL}--promote"

            else
                make "${TOOL}--push"
            fi
        done
        make metadata.json--push

    - name: Store logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: logs.zip
        path: "**/build.log"
